{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "140a8160-728a-4ed5-94de-70406d8cbeeb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Dataset Loaded Successfully\n",
      "\n",
      "Training Samples : 14610\n",
      "Testing Samples : 3653\n",
      "\n",
      " ========================================\n",
      "Linear Regression\n",
      "========================================\n",
      "MAE : 6.566\n",
      "RMSE: 10.734\n",
      "R2 : 0.9999\n",
      "\n",
      " ========================================\n",
      "Decision Tree\n",
      "========================================\n",
      "MAE : 768.193\n",
      "RMSE: 1172.827\n",
      "R2 : -0.3431\n",
      "\n",
      " ========================================\n",
      "Random Forest\n",
      "========================================\n",
      "MAE : 769.261\n",
      "RMSE: 1174.389\n",
      "R2 : -0.3467\n",
      "\n",
      "Model Saved Successfully\n",
      "\n",
      "stock_model.pkl Created\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.tree import DecisionTreeRegressor\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "\n",
    "from sklearn.metrics import (\n",
    "    mean_absolute_error,\n",
    "    mean_squared_error,\n",
    "    r2_score\n",
    ")\n",
    "\n",
    "# =====================================\n",
    "# Load Dataset\n",
    "# =====================================\n",
    "\n",
    "df = pd.read_csv(r\"C:\\Users\\Divyansh Babbar\\OneDrive\\Desktop\\Divyansh Work\\sp500.csv\")\n",
    "\n",
    "print(\"\\nDataset Loaded Successfully\\n\")\n",
    "\n",
    "# =====================================\n",
    "# Convert Date\n",
    "# =====================================\n",
    "\n",
    "df[\"Date\"] = pd.to_datetime(df[\"Date\"])\n",
    "\n",
    "df[\"Year\"] = df[\"Date\"].dt.year\n",
    "df[\"Month\"] = df[\"Date\"].dt.month\n",
    "df[\"Day\"] = df[\"Date\"].dt.day\n",
    "\n",
    "# =====================================\n",
    "# Feature Engineering\n",
    "# =====================================\n",
    "\n",
    "df[\"Previous_Close\"] = df[\"Close\"].shift(1)\n",
    "\n",
    "df[\"MA7\"] = df[\"Close\"].rolling(7).mean()\n",
    "\n",
    "df[\"MA30\"] = df[\"Close\"].rolling(30).mean()\n",
    "\n",
    "df[\"Daily_Return\"] = df[\"Close\"].pct_change()\n",
    "\n",
    "df.dropna(inplace=True)\n",
    "\n",
    "# =====================================\n",
    "# Select Features\n",
    "# =====================================\n",
    "\n",
    "X = df[\n",
    "    [\n",
    "        \"Open\",\n",
    "        \"High\",\n",
    "        \"Low\",\n",
    "        \"Volume\",\n",
    "        \"Previous_Close\",\n",
    "        \"MA7\",\n",
    "        \"MA30\",\n",
    "        \"Daily_Return\",\n",
    "        \"Year\",\n",
    "        \"Month\",\n",
    "        \"Day\"\n",
    "    ]\n",
    "]\n",
    "\n",
    "y = df[\"Close\"]\n",
    "\n",
    "# =====================================\n",
    "# Train Test Split\n",
    "# =====================================\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X,\n",
    "    y,\n",
    "    test_size=0.20,\n",
    "    shuffle=False\n",
    ")\n",
    "\n",
    "print(\"Training Samples :\", len(X_train))\n",
    "print(\"Testing Samples :\", len(X_test))\n",
    "\n",
    "# =====================================\n",
    "# Function\n",
    "# =====================================\n",
    "\n",
    "def evaluate(model, name):\n",
    "\n",
    "    prediction = model.predict(X_test)\n",
    "\n",
    "    mae = mean_absolute_error(y_test, prediction)\n",
    "\n",
    "    mse = mean_squared_error(y_test, prediction)\n",
    "\n",
    "    rmse = np.sqrt(mse)\n",
    "\n",
    "    r2 = r2_score(y_test, prediction)\n",
    "\n",
    "    print(\"\\n\", \"=\"*40)\n",
    "    print(name)\n",
    "    print(\"=\"*40)\n",
    "\n",
    "    print(\"MAE :\", round(mae,3))\n",
    "    print(\"RMSE:\", round(rmse,3))\n",
    "    print(\"R2 :\", round(r2,4))\n",
    "\n",
    "    return r2\n",
    "\n",
    "# =====================================\n",
    "# Linear Regression\n",
    "# =====================================\n",
    "\n",
    "lr = LinearRegression()\n",
    "\n",
    "lr.fit(X_train, y_train)\n",
    "\n",
    "lr_score = evaluate(lr,\"Linear Regression\")\n",
    "\n",
    "# =====================================\n",
    "# Decision Tree\n",
    "# =====================================\n",
    "\n",
    "dt = DecisionTreeRegressor(\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "dt.fit(X_train,y_train)\n",
    "\n",
    "dt_score = evaluate(dt,\"Decision Tree\")\n",
    "\n",
    "# =====================================\n",
    "# Random Forest\n",
    "# =====================================\n",
    "\n",
    "rf = RandomForestRegressor(\n",
    "\n",
    "    n_estimators=300,\n",
    "\n",
    "    random_state=42,\n",
    "\n",
    "    max_depth=12\n",
    "\n",
    ")\n",
    "\n",
    "rf.fit(X_train,y_train)\n",
    "\n",
    "rf_score = evaluate(rf,\"Random Forest\")\n",
    "\n",
    "# =====================================\n",
    "# Save Best Model\n",
    "# =====================================\n",
    "\n",
    "joblib.dump(\n",
    "\n",
    "    rf,\n",
    "\n",
    "    \"stock_model.pkl\"\n",
    "\n",
    ")\n",
    "\n",
    "print(\"\\nModel Saved Successfully\")\n",
    "\n",
    "print(\"\\nstock_model.pkl Created\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "216bed95-5c54-4b18-b937-932e9660174b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6f0c86d9-7cea-4494-ab46-85f312df5c8f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3634415-5cc5-4b85-9e65-a7e016403f2c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
